### ISSUE TITLE
failed to run custom build command for `hdf5-sys v0.8.1 (https://github.com/aldanor/hdf5-rust/#fb96296e)`

### ISSUE THREAD

**Issue by Morning4Star** [Rikorose/DeepFilterNet#195] opened 2022-11-28 08:28 UTC
maturin develop --release -m pyDF-data/Cargo.toml.I have a problem with this step.My environment is windows11.

The following is the error message:
📦 Including license file "D:\DeepFilterNet-main\pyDF-data\LICENSE"
📦 Including license file "D:\DeepFilterNet-main\pyDF-data\LICENSE-APACHE"
📦 Including license file "D:\DeepFilterNet-main\pyDF-data\LICENSE-MIT"
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings
🐍 Found CPython 3.9 at D:\Anaconda3\envs\pytorch-gpu\python.exe
Requirement already satisfied: numpy>=1.22 in d:\anaconda3\envs\pytorch-gpu\lib\site-packages (1.23.3)
   Compiling serde_derive v1.0.147
   Compiling winapi-x86_64-pc-windows-gnu v0.4.0
   Compiling libm v0.2.6
   Compiling num-traits v0.2.15
   Compiling winapi v0.3.9
   Compiling memchr v2.5.0
   Compiling serde v1.0.147
   Compiling winreg v0.10.1
   Compiling getrandom v0.2.8
   Compiling regex-syntax v0.6.28
   Compiling crossbeam-utils v0.8.12
   Compiling proc-macro-error-attr v1.0.4
   Compiling crossbeam-epoch v0.9.11
   Compiling proc-macro-error v1.0.4
   Compiling rand_core v0.6.4
   Compiling rayon-core v1.9.3
   Compiling parking_lot_core v0.8.5
   Compiling ppv-lite86 v0.2.17
   Compiling instant v0.1.12
   Compiling hdf5-types v0.8.1 (https://github.com/aldanor/hdf5-rust/#fb96296e)
   Compiling rayon v1.5.3
   Compiling tinyvec_macros v0.1.0
   Compiling ascii v1.1.0
   Compiling serde_json v1.0.87
   Compiling hdf5 v0.8.1 (https://github.com/aldanor/hdf5-rust/#fb96296e)
   Compiling byteorder v1.4.3
   Compiling rand_chacha v0.3.1
   Compiling aho-corasick v0.7.19
   Compiling rand v0.8.5
   Compiling crossbeam-channel v0.5.6
   Compiling crossbeam-deque v0.8.2
   Compiling num_cpus v1.14.0
   Compiling ogg v0.8.0
   Compiling tinyvec v1.6.0
   Compiling bitflags v1.3.2
   Compiling itoa v1.0.4
   Compiling hdf5-derive v0.8.1 (https://github.com/aldanor/hdf5-rust/#fb96296e)
   Compiling lazy_static v1.4.0
   Compiling paste v1.0.9
   Compiling ryu v1.0.11
   Compiling ahash v0.7.6
   Compiling num-integer v0.1.45
   Compiling regex v1.7.0
   Compiling rand_distr v0.4.3
   Compiling rand_xoshiro v0.6.0
   Compiling hound v3.5.0
   Compiling transpose v0.2.2
   Compiling primal-check v0.3.3
   Compiling lewton v0.10.2
   Compiling roots v0.0.7
   Compiling claxon v0.4.3
   Compiling libloading v0.7.4
   Compiling parking_lot v0.11.2
   Compiling hdf5-sys v0.8.1 (https://github.com/aldanor/hdf5-rust/#fb96296e)
error: failed to run custom build command for `hdf5-sys v0.8.1 (https://github.com/aldanor/hdf5-rust/#fb96296e)`

Caused by:
  process didn't exit successfully: `D:\DeepFilterNet-main\target\release\build\hdf5-sys-a655ef67c64ed6b4\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Unable to locate HDF5 root directory and/or headers.', D:\Rust\.rustup\git\checkouts\hdf5-rust-c1072d7a2617f7d8\fb96296\hdf5-sys\build.rs:552:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit code: 101": `"cargo" "rustc" "--release" "--manifest-path" "D:\\DeepFilterNet-main\\pyDF-data\\Cargo.toml" "--message-format" "json" "--lib" "--" "-C" "link-arg=-s"`

**Comment by Morning4Star** [comment] 2022-11-28 09:11
I think I have it installed here.
<img width="862" alt="image" src="https://user-images.githubusercontent.com/117175658/204238445-18f75b7a-aa76-46c5-9768-6741d1cf1320.png">

**Comment by Rikorose** [comment] 2022-11-28 09:13
But not development headers. Duplicate of #32

**Closed by Rikorose** 2022-11-28 09:13 UTC
