### ISSUE TITLE
Buffer length of real-time inference

### ISSUE THREAD

**Issue by aaronhsueh0506** [Rikorose/DeepFilterNet#77] opened 2022-05-09 02:31 UTC
Hi Rikorose,

Sorry to bother you again,
I have transfered the code to keras and try to inference like real-time.

I found a few situations I want to ask,
1. In enhance.py, the flow looks like feeding the entire signal into the model? It is like a offline inference?
2. I try to do a real-time inference, this is my flow.
    - Feeding a fixed-length buffer (with a look-ahead of 1 frame)
    - Getting the same length output
    - Taking the second last frame output as the real-time processed frame.

    When I change the buffer length to inference, the effect is good while the length is 100 or 300. 
    But when I change the buffer length to 10 frames, the effect sounds bad. 
    When I try to do the real-time inference, what is the minimum buffer length?

Thanks,

**Comment by Rikorose** [comment] 2022-05-09 06:03
Currently, enhance.py processes a whole audio file. The model itself is designed for real-time usage, but I currently don't have a working implementation yet. In #13, I have implemented the real-time loop in rust, but the 2nd stage has a bug resulting in worse audio quality.

For real-time usage, you need to get all the temporal buffer right, especially for all the convolutions and the DeepFilter module.

**Comment by Rikorose** [comment] 2022-05-13 07:03
Duplicate of #76

**Closed by Rikorose** 2022-05-13 07:03 UTC

**Comment by JulienBalianSonos** [comment] 2022-09-05 11:16
Hello Hendrik,
I would like to first congrats and thank you for the great research you have published and open-sourced with DeepFilterNet (1 & 2).

We have been impressed by the quality and the results of your work (our internal retraining/benchmarks with this solution seems promising).

We would like to go further and understand in-depth the on-device consumption of such solution.

Seeing that you already almost did the work in this PR with tract inference engine in full rust:
- I was wondering if you could expand the blockers that lead you to let this branch stale.
- I saw your comments here: https://github.com/Rikorose/DeepFilterNet/issues/77 and was willing to better understand how we could help on this ?

Also, a rebase or merge from main into this branch seems needed to revive this branch, do you confirm ?
